// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbAsLnJXFVs9HTA7DRpogEypdexHvyhP8',
    appId: '1:993153447500:web:3e7462149c9cbc0f32e6e9',
    messagingSenderId: '993153447500',
    projectId: 'ict602-marks',
    authDomain: 'ict602-marks.firebaseapp.com',
    storageBucket: 'ict602-marks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2qeGiZrN23QDKMTmARCL3FRUqbCPMv6w',
    appId: '1:993153447500:android:2fcab58688e7ec4632e6e9',
    messagingSenderId: '993153447500',
    projectId: 'ict602-marks',
    storageBucket: 'ict602-marks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmpKvJVhKYfkvpT-s_WdQJw_fepdM87w',
    appId: '1:993153447500:ios:26c9373ff67ca44532e6e9',
    messagingSenderId: '993153447500',
    projectId: 'ict602-marks',
    storageBucket: 'ict602-marks.firebasestorage.app',
    iosBundleId: 'com.example.ict602Marks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmpKvJVhKYfkvpT-s_WdQJw_fepdM87w',
    appId: '1:993153447500:ios:26c9373ff67ca44532e6e9',
    messagingSenderId: '993153447500',
    projectId: 'ict602-marks',
    storageBucket: 'ict602-marks.firebasestorage.app',
    iosBundleId: 'com.example.ict602Marks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbAsLnJXFVs9HTA7DRpogEypdexHvyhP8',
    appId: '1:993153447500:web:79a282ad1a03ee7732e6e9',
    messagingSenderId: '993153447500',
    projectId: 'ict602-marks',
    authDomain: 'ict602-marks.firebaseapp.com',
    storageBucket: 'ict602-marks.firebasestorage.app',
  );
}
