import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

// Import the file generated by FlutterFire CLI
import 'firebase_options.dart';

// Import our auth gate (make sure you've created auth_gate.dart)
import 'auth_gate.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for the current platform (Windows/Web/Android)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ICT602MarksApp());
}

class ICT602MarksApp extends StatelessWidget {
  const ICT602MarksApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ICT602 Marks',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      // ⬇️ This now decides: show Login or Student/Lecturer home
      home: AuthGate(),
    );
  }
}
